export const PRICING_TIERS = [
  {
    id: 'professional',
    price: 25000,
    offerPrice: 8500,
    offerLimit: 100,
    placesLeft: 55,
    popular: true,
    lifetime: true,
    nameKey: 'onboarding.pricing.professional',
    descKey: 'onboarding.pricing.professionalDesc',
    featuresKey: 'onboarding.pricing.professionalFeatures',
    ctaKey: 'onboarding.pricing.select',
  },
  {
    id: 'premium',
    price: 45000,
    offerPrice: 25000,
    offerLimit: 100,
    placesLeft: 67,
    popular: false,
    lifetime: true,
    nameKey: 'onboarding.pricing.premium',
    descKey: 'onboarding.pricing.premiumDesc',
    featuresKey: 'onboarding.pricing.premiumFeatures',
    ctaKey: 'onboarding.pricing.select',
  },
  {
    id: 'enterprise',
    price: 0,
    offerPrice: 0,
    offerLimit: 0,
    placesLeft: 0,
    popular: false,
    lifetime: false,
    nameKey: 'onboarding.pricing.enterprise',
    priceKey: 'onboarding.pricing.enterprisePrice',
    descKey: 'onboarding.pricing.enterpriseDesc',
    featuresKey: 'onboarding.pricing.enterpriseFeatures',
    ctaKey: 'onboarding.pricing.contactUs',
  },
]
